const Data = {
  all:[
    { id: 1, img: '/assets/tv1.jpg', name: 'Samsung QLED', price: 1200, discount: 0, slug: 'Samsung QLED' },
    { id: 2, img: '/assets/tv2.jpg', name: 'LG OLED', price: 1500, discount: 0, slug: 'LG OLED' },
    { id: 3, img: '/assets/tv3.jpg', name: 'Sony Bravia', price: 1300, discount: 0, slug: 'Sony Bravia' },
    { id: 4, img: '/assets/tv4.jpg', name: 'TCL 6-Series', price: 900, discount: 0, slug: 'TCL 6-Series' },
    { id: 5, img: '/assets/tv5.jpg', name: 'Vizio P-Series', price: 1000, discount: 0, slug: 'Vizio P-Series' },
    { id: 6, img: '/assets/tv6.jpg', name: 'Hisense H9G', price: 800, discount: 0, slug: 'Hisense H9G' },
    { id: 7, img: '/assets/laptop1.jpg', name: 'MacBook Pro', price: 2500, discount: 0, slug: 'MacBook Pro' },
    { id: 8, img: '/assets/laptop2.jpg', name: 'Dell XPS 13', price: 1200, discount: 0, slug: 'Dell XPS 13' },
    { id: 9, img: '/assets/laptop3.jpg', name: 'HP Spectre x360', price: 1400, discount: 0, slug: 'HP Spectre x360' },
    { id: 10, img: '/assets/laptop4.jpg', name: 'Lenovo ThinkPad X1', price: 1600, discount: 0, slug: 'Lenovo ThinkPad X1' },
    { id: 11, img: '/assets/laptop5.jpg', name: 'Asus ZenBook', price: 1100, discount: 0, slug: 'Asus ZenBook' },
    { id: 12, img: '/assets/laptop6.jpg', name: 'Microsoft Surface Laptop 4', price: 1300, discount: 0, slug: 'Microsoft Surface Laptop 4' },
    { id: 13, img: '/assets/phone1.jpg', name: 'iPhone 12', price: 999, discount: 0, slug: 'iPhone 12' },
    { id: 14, img: '/assets/phone2.jpg', name: 'Samsung Galaxy S21', price: 799, discount: 0, slug: 'Samsung Galaxy S21' },
    { id: 15, img: '/assets/phone3.jpg', name: 'Google Pixel 5', price: 699, discount: 0, slug: 'Google Pixel 5' },
    { id: 16, img: '/assets/phone4.jpg', name: 'OnePlus 9', price: 729, discount: 0, slug: 'OnePlus 9' },
    { id: 17, img: '/assets/phone5.jpg', name: 'Sony Xperia 1', price: 949, discount: 0, slug: 'Sony Xperia 1' },
    { id: 18, img: '/assets/phone6.jpg', name: 'Xiaomi Mi 11', price: 749, discount: 0, slug: 'Xiaomi Mi 11' },
    { id: 19, img: '/assets/cooler1.jpg', name: 'Noctua NH-D15', price: 90, discount: 0, slug: 'Noctua NH-D15' },
    { id: 20, img: '/assets/cooler2.jpg', name: 'Cooler Master Hyper 212 EVO', price: 35, discount: 0, slug: 'Cooler Master Hyper 212 EVO' },
    { id: 21, img: '/assets/cooler3.jpg', name: 'be quiet! Dark Rock Pro 4', price: 80, discount: 0, slug: 'be quiet! Dark Rock Pro 4' },
    { id: 22, img: '/assets/cooler4.jpg', name: 'Corsair H100i RGB Platinum', price: 160, discount: 0, slug: 'Corsair H100i RGB Platinum' },
    { id: 23, img: '/assets/cooler5.jpg', name: 'NZXT Kraken X63', price: 150, discount: 0, slug: 'NZXT Kraken X63' },
    { id: 24, img: '/assets/cooler6.jpg', name: 'Arctic Freezer 34 eSports DUO', price: 50, discount: 0, slug: 'Arctic Freezer 34 eSports DUO' },
    { id: 25, img: '/assets/headset1.jpg', name: 'HyperX Cloud II', price: 100, discount: 0, slug: 'HyperX Cloud II' },
    { id: 26, img: '/assets/headset2.jpg', name: 'SteelSeries Arctis 7', price: 150, discount: 0, slug: 'SteelSeries Arctis 7' },
    { id: 27, img: '/assets/headset3.jpg', name: 'Logitech G Pro X', price: 130, discount: 0, slug: 'Logitech G Pro X' },
    { id: 28, img: '/assets/headset4.jpg', name: 'Razer Kraken X', price: 50, discount: 0, slug: 'Razer Kraken X' },
    { id: 29, img: '/assets/headset5.jpg', name: 'Corsair HS60 Pro', price: 70, discount: 0, slug: 'Corsair HS60 Pro' },
    { id: 30, img: '/assets/headset6.jpg', name: 'Astro A50', price: 300, discount: 0, slug: 'Astro A50' },
    { id: 31, img: '/assets/pc1.jpg', name: 'Alienware Aurora R12', price: 2000, discount: 0, slug: 'Alienware Aurora R12' },
    { id: 32, img: '/assets/pc2.jpg', name: 'HP Omen 30L', price: 1800, discount: 0, slug: 'HP Omen 30L' },
    { id: 33, img: '/assets/pc3.jpg', name: 'CyberPowerPC Gamer Supreme', price: 1600, discount: 0, slug: 'CyberPowerPC Gamer Supreme' },
    { id: 34, img: '/assets/pc4.jpg', name: 'MSI MEG Trident X', price: 2200, discount: 0, slug: 'MSI MEG Trident X' },
    { id: 35, img: '/assets/pc5.jpg', name: 'Corsair One Pro i200', price: 2500, discount: 0, slug: 'Corsair One Pro i200' },
    { id: 36, img: '/assets/pc6.jpg', name: 'ASUS ROG Strix GA15', price: 1500, discount: 0, slug: 'ASUS ROG Strix GA15' },
  ],
  tv: [
    { id: 1, img: '/assets/tv1.jpg', name: 'Samsung QLED', price: 1200, discount: 0, slug: 'Samsung QLED' },
    { id: 2, img: '/assets/tv2.jpg', name: 'LG OLED', price: 1500, discount: 0, slug: 'LG OLED' },
    { id: 3, img: '/assets/tv3.jpg', name: 'Sony Bravia', price: 1300, discount: 0, slug: 'Sony Bravia' },
    { id: 4, img: '/assets/tv4.jpg', name: 'TCL 6-Series', price: 900, discount: 0, slug: 'TCL 6-Series' },
    { id: 5, img: '/assets/tv5.jpg', name: 'Vizio P-Series', price: 1000, discount: 0, slug: 'Vizio P-Series' },
    { id: 6, img: '/assets/tv6.jpg', name: 'Hisense H9G', price: 800, discount: 0, slug: 'Hisense H9G' },
  ],
  laptops: [
    { id: 7, img: '/assets/laptop1.jpg', name: 'MacBook Pro', price: 2500, discount: 0, slug: 'MacBook Pro' },
    { id: 8, img: '/assets/laptop2.jpg', name: 'Dell XPS 13', price: 1200, discount: 0, slug: 'Dell XPS 13' },
    { id: 9, img: '/assets/laptop3.jpg', name: 'HP Spectre x360', price: 1400, discount: 0, slug: 'HP Spectre x360' },
    { id: 10, img: '/assets/laptop4.jpg', name: 'Lenovo ThinkPad X1', price: 1600, discount: 0, slug: 'Lenovo ThinkPad X1' },
    { id: 11, img: '/assets/laptop5.jpg', name: 'Asus ZenBook', price: 1100, discount: 0, slug: 'Asus ZenBook' },
    { id: 12, img: '/assets/laptop6.jpg', name: 'Microsoft Surface Laptop 4', price: 1300, discount: 0, slug: 'Microsoft Surface Laptop 4' },
  ],
  phones: [
    { id: 13, img: '/assets/phone1.jpg', name: 'iPhone 12', price: 999, discount: 0, slug: 'iPhone 12' },
    { id: 14, img: '/assets/phone2.jpg', name: 'Samsung Galaxy S21', price: 799, discount: 0, slug: 'Samsung Galaxy S21' },
    { id: 15, img: '/assets/phone3.jpg', name: 'Google Pixel 5', price: 699, discount: 0, slug: 'Google Pixel 5' },
    { id: 16, img: '/assets/phone4.jpg', name: 'OnePlus 9', price: 729, discount: 0, slug: 'OnePlus 9' },
    { id: 17, img: '/assets/phone5.jpg', name: 'Sony Xperia 1', price: 949, discount: 0, slug: 'Sony Xperia 1' },
    { id: 18, img: '/assets/phone6.jpg', name: 'Xiaomi Mi 11', price: 749, discount: 0, slug: 'Xiaomi Mi 11' },
  ],
  cpuCoolers: [
    { id: 19, img: '/assets/cooler1.jpg', name: 'Noctua NH-D15', price: 90, discount: 0, slug: 'Noctua NH-D15' },
    { id: 20, img: '/assets/cooler2.jpg', name: 'Cooler Master Hyper 212 EVO', price: 35, discount: 0, slug: 'Cooler Master Hyper 212 EVO' },
    { id: 21, img: '/assets/cooler3.jpg', name: 'be quiet! Dark Rock Pro 4', price: 80, discount: 0, slug: 'be quiet! Dark Rock Pro 4' },
    { id: 22, img: '/assets/cooler4.jpg', name: 'Corsair H100i RGB Platinum', price: 160, discount: 0, slug: 'Corsair H100i RGB Platinum' },
    { id: 23, img: '/assets/cooler5.jpg', name: 'NZXT Kraken X63', price: 150, discount: 0, slug: 'NZXT Kraken X63' },
    { id: 24, img: '/assets/cooler6.jpg', name: 'Arctic Freezer 34 eSports DUO', price: 50, discount: 0, slug: 'Arctic Freezer 34 eSports DUO' },
  ],
  headsets: [
    { id: 25, img: '/assets/headset1.jpg', name: 'HyperX Cloud II', price: 100, discount: 0, slug: 'HyperX Cloud II' },
    { id: 26, img: '/assets/headset2.jpg', name: 'SteelSeries Arctis 7', price: 150, discount: 0, slug: 'SteelSeries Arctis 7' },
    { id: 27, img: '/assets/headset3.jpg', name: 'Logitech G Pro X', price: 130, discount: 0, slug: 'Logitech G Pro X' },
    { id: 28, img: '/assets/headset4.jpg', name: 'Razer Kraken X', price: 50, discount: 0, slug: 'Razer Kraken X' },
    { id: 29, img: '/assets/headset5.jpg', name: 'Corsair HS60 Pro', price: 70, discount: 0, slug: 'Corsair HS60 Pro' },
    { id: 30, img: '/assets/headset6.jpg', name: 'Astro A50', price: 300, discount: 0, slug: 'Astro A50' },
  ],
  pcs: [
    { id: 31, img: '/assets/pc1.jpg', name: 'Alienware Aurora R12', price: 2000, discount: 0, slug: 'Alienware Aurora R12' },
    { id: 32, img: '/assets/pc2.jpg', name: 'HP Omen 30L', price: 1800, discount: 0, slug: 'HP Omen 30L' },
    { id: 33, img: '/assets/pc3.jpg', name: 'CyberPowerPC Gamer Supreme', price: 1600, discount: 0, slug: 'CyberPowerPC Gamer Supreme' },
    { id: 34, img: '/assets/pc4.jpg', name: 'MSI MEG Trident X', price: 2200, discount: 0, slug: 'MSI MEG Trident X' },
    { id: 35, img: '/assets/pc5.jpg', name: 'Corsair One Pro i200', price: 2500, discount: 0, slug: 'Corsair One Pro i200' },
    { id: 36, img: '/assets/pc6.jpg', name: 'ASUS ROG Strix GA15', price: 1500, discount: 0, slug: 'ASUS ROG Strix GA15' },
  ],
  todaysDeals: [
    { id: 2, img: '/assets/tv2.jpg', name: 'LG OLED', price: 1500, discount: 20 },
    { id: 9, img: '/assets/laptop3.jpg', name:'HP Spectre x360', price: 1400, discount: 15 },
    { id: 13, img: '/assets/phone1.jpg', name: 'iPhone 12', price: 999, discount: 25 },
    { id: 19, img: '/assets/cooler1.jpg', name: 'Noctua NH-D15', price: 90, discount: 30 },
    { id: 26, img: '/assets/headset2.jpg', name: 'SteelSeries Arctis 7', price: 150, discount: 10 },
    { id: 33, img: '/assets/pc3.jpg', name: 'CyberPowerPC Gamer Supreme', price: 1600, discount: 20 },
  ],
  seasonalOffers: [
    { id: 1, img: '/assets/tv1.jpg', name: 'Samsung QLED', price: 1200, discount: 30 },
    { id: 7, img: '/assets/laptop1.jpg', name: 'MacBook Pro', price: 2500, discount: 20 },
    { id: 14, img: '/assets/phone2.jpg', name: 'Samsung Galaxy S21', price: 799, discount: 35 },
    { id: 21, img: '/assets/cooler3.jpg', name: 'be quiet! Dark Rock Pro 4', price: 80, discount: 40},
    { id: 25, img: '/assets/headset1.jpg', name: 'HyperX Cloud II', price: 100, discount: 25},
    { id: 31, img: '/assets/pc1.jpg', name: 'Alienware Aurora R12', price: 2000, discount: 30},
  ],
  topSellers: [
    { id: 2, img: '/assets/tv2.jpg', name: 'LG OLED', price: 1500, rating: 4.8 },
    { id: 7, img: '/assets/laptop1.jpg', name: 'MacBook Pro', price: 2500,rating: 4.7 },
    { id: 13, img: '/assets/phone1.jpg', name: 'iPhone 12', price: 999, rating: 4.9 },
    { id: 19, img: '/assets/cooler1.jpg', name: 'Noctua NH-D15', price: 90, rating: 4.8 },
    { id: 26, img: '/assets/headset2.jpg', name: 'SteelSeries Arctis 7', price: 150, rating: 4.6 },
    { id: 33, img: '/assets/pc3.jpg', name: 'CyberPowerPC Gamer Supreme', price: 1600, rating: 4.6 },
  ],
};

export default Data